services:
  immich-server:
    labels:
      net.unraid.docker.managed: 'composeman'
      net.unraid.docker.icon: 'https://avatars.githubusercontent.com/u/109746326?s=200&v=4'
      net.unraid.docker.webui: 'http://172.21.8.111:2283'
      net.unraid.docker.shell: ''
  immich-machine-learning:
    labels:
      net.unraid.docker.managed: 'composeman'
      net.unraid.docker.icon: 'https://www.pngall.com/wp-content/uploads/15/Machine-Learning-180x180.png'
      net.unraid.docker.webui: ''
      net.unraid.docker.shell: ''
  redis:
    labels:
      net.unraid.docker.managed: 'composeman'
      net.unraid.docker.icon: 'https://1000logos.net/wp-content/uploads/2020/08/Redis-Logo-360x225.png'
      net.unraid.docker.webui: ''
      net.unraid.docker.shell: ''
  database:
    labels:
      net.unraid.docker.managed: 'composeman'
      net.unraid.docker.icon: 'https://rtfm.co.ua/wp-content/uploads/2017/10/postgresql-logo.png'
      net.unraid.docker.webui: ''
      net.unraid.docker.shell: ''
  immich-public-proxy:
    labels:
      net.unraid.docker.managed: 'composeman'
      net.unraid.docker.icon: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSgkqWgQc0vtaavumIgSKhyrRtX7oQeCMxoCA&s'
      net.unraid.docker.webui: 'http://172.21.8.116:3033'
      net.unraid.docker.shell: ''
  immich-prometheus:
    labels:
      net.unraid.docker.managed: 'composeman'
      net.unraid.docker.icon: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/38/Prometheus_software_logo.svg/242px-Prometheus_software_logo.svg.png'
      net.unraid.docker.webui: 'http://172.21.8.117:9090'
      net.unraid.docker.shell: ''
  immich-grafana:
    labels:
      net.unraid.docker.managed: 'composeman'
      net.unraid.docker.icon: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a1/Grafana_logo.svg/250px-Grafana_logo.svg.png'
      net.unraid.docker.webui: 'http://172.21.8.118:3000'
      net.unraid.docker.shell: ''
  pgadmin:
    labels:
      net.unraid.docker.managed: 'composeman'
      net.unraid.docker.icon: 'https://static-00.iconduck.com/assets.00/pgadmin-icon-512x512-ghd4xf2u.png'
      net.unraid.docker.webui: 'http://172.21.8.119:8888'
      net.unraid.docker.shell: ''
  immich-kiosk:
    labels:
      net.unraid.docker.managed: 'composeman'
      net.unraid.docker.icon: 'https://raw.githubusercontent.com/nwithan8/unraid_templates/master/images/immich-kiosk-icon.png'
      net.unraid.docker.webui: 'http://172.21.8.120:3000'
      net.unraid.docker.shell: ''